pos/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.get_transaction, name='get_transaction'),
	path('<int:transaction_id>/delete-transaction/', views.transactionDelete, name='delete_transaction'),
	path('<int:deposit_id>/delete-deposit/', views.depositDelete, name='delete_deposit'),
	path('ajax/load-subcat/', views.load_subcat, name='ajax_load_subcat'),
	path('ajax/load-items/', views.load_items, name='ajax_load_items'),
]

tradingpost/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('tradingpost/', include('pos.urls')),
    path('admin/', admin.site.urls),
]

pos/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.utils.timezone import now

# Create your models here.
class Customer(models.Model):
	camperID = models.IntegerField(primary_key=True)
	lastName = models.CharField(max_length=255)
	firstName = models.CharField(max_length=255)
	beginBalance = models.DecimalField(max_digits=6, decimal_places=2)
	currentBalance = models.DecimalField(max_digits=6, decimal_places=2)
	endBalance = models.DecimalField(blank=True, null=True, max_digits=6, decimal_places=2)
	donateBalance = models.DecimalField(blank=True, null=True, max_digits=6, decimal_places=2)
	returnedBalance = models.DecimalField(blank=True, null=True, max_digits=6, decimal_places=2)
	downloadBalance = models.BooleanField()

	def __str__(self):
		return str(self.lastName + ", " + self.firstName)

class Category(models.Model):
	parentID = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)
	categoryID = models.AutoField(primary_key=True)
	categoryDesc = models.CharField(max_length=255)

	def __str__(self):
		return self.categoryDesc

	class Meta:
		verbose_name_plural = "Categories"

class Item(models.Model):
	itemID = models.AutoField(primary_key=True)
	categoryID = models.ForeignKey(Category, on_delete=models.CASCADE)
	itemDesc = models.CharField(max_length=255)
	itemPrice = models.DecimalField(max_digits=5, decimal_places=2)

	def __str__(self):
		return self.itemDesc

class Style(models.Model):
	styleID = models.AutoField(primary_key=True)
	itemID = models.ForeignKey(Item, on_delete=models.CASCADE)
	styleDesc = models.CharField(max_length=255)

	def __str__(self):
		return self.styleDesc

class Color(models.Model):
	colorID = models.AutoField(primary_key=True)
	colorDesc = models.CharField(max_length=255)

	def __str__(self):
		return self.colorDesc

class Size(models.Model):
	sizeID = models.AutoField(primary_key=True)
	sizeDesc = models.CharField(max_length = 255)

	def __str__(self):
		return self.sizeDesc

class ItemColor(models.Model):
	itemID = models.ManyToManyField(Item)
	colorID = models.ManyToManyField(Color)

class ItemSize(models.Model):
	itemID = models.ManyToManyField(Item)
	sizeID = models.ManyToManyField(Size)

class Transaction(models.Model):
	transactionID = models.AutoField(primary_key=True)
	submitUser = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
	camperID = models.ForeignKey(Customer, on_delete=models.CASCADE)
	transactionDate = models.DateTimeField(default=now)
	#transactionWeek = models.ForeignKey(Registration, on_delete=models.CASCADE)
	#itemCategory = models.ForeignKey(Category, on_delete=models.CASCADE) #Redundant, each item only has one category
	itemID = models.ForeignKey(Item, on_delete=models.CASCADE)
	#itemStyle = models.ForeignKey(Style, on_delete=models.CASCADE)
	itemColor = models.ForeignKey(Color, blank=True, null=True, on_delete=models.CASCADE)
	itemSize = models.ForeignKey(ItemSize, blank=True, null=True, on_delete=models.CASCADE)
	transactionNotes = models.CharField(blank=True, null=True, max_length=255)

	def calc_current_balance(ID):
		t = Transaction.objects.filter(camperID=ID).select_related('itemID')
		balance = list(Customer.objects.filter(pk=ID).values('beginBalance'))
		balance = balance[0]['beginBalance']
		deposit_sum = 0
		if Deposit.objects.filter(camperID=ID):
			deposit_sum = Deposit.objects.filter(camperID=ID)
			deposit_sum = deposit_sum.aggregate(Sum('depositAmount'))
			deposit_sum = deposit_sum['depositAmount__sum']

		if t:
			trans_sum = t.aggregate(Sum('itemID__itemPrice'))
			trans_sum = trans_sum['itemID__itemPrice__sum']

			curr_balance = balance - trans_sum + deposit_sum
			Customer.objects.filter(pk=ID).update(currentBalance = curr_balance)

			return

		else:
			curr_balance = balance + deposit_sum
			Customer.objects.filter(pk=ID).update(currentBalance = curr_balance)
			return

class Deposit(models.Model):
	depositID = models.AutoField(primary_key=True)
	camperID = models.ForeignKey(Customer, on_delete=models.CASCADE)
	depositDate = models.DateTimeField(default=now)
	depositAmount = models.DecimalField(max_digits=6, decimal_places=2)
	depositNotes = models.CharField(blank=True, null=True, max_length=255)

pos/forms.py
from django import forms
from .models import Category, Transaction, Item, Customer

class TransactionForm(forms.Form):
	#class Meta:
	#	model = Transaction
	#	fields = ['camperID', 'transactionDate', 'itemID', 'itemColor']
	Camper = forms.ModelChoiceField(queryset=Customer.objects.all().order_by('lastName'))

class PurchaseForm(forms.Form):
	category = forms.ModelChoiceField(queryset=Category.objects.filter(parentID__isnull=True).order_by('categoryDesc'))
	subcategory = forms.ModelChoiceField(queryset=Category.objects.filter(parentID__isnull=False).order_by('categoryDesc'))
	item = forms.ModelChoiceField(queryset=Item.objects.all().order_by('itemDesc'))

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['subcategory'].queryset = Category.objects.none()
		self.fields['item'].queryset = Item.objects.none()

class DepositForm(forms.Form):
	deposit = forms.DecimalField(max_digits=6, decimal_places=2)
	notes = forms.CharField(max_length=255)

pos/views.py
from datetime import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic.edit import DeleteView

from .forms import TransactionForm, PurchaseForm, DepositForm
from .models import Customer, Category, Item, Transaction, Deposit

def transactionDelete(request, transaction_id):
	object = get_object_or_404(Transaction, pk=transaction_id)
	object.delete()

	form = TransactionForm()
	return HttpResponseRedirect((request.META.get('HTTP_REFERER', '/'))) 

def depositDelete(request, deposit_id):
	object = get_object_or_404(Deposit, pk=deposit_id)
	object.delete()

	form = TransactionForm()
	return HttpResponseRedirect((request.META.get('HTTP_REFERER', '/'))) 

def load_subcat(request):
	category = request.GET.get('category')
	subcats = Category.objects.filter(parentID=category).order_by('categoryDesc')
	return render(request, 'pos/subcat_dropdown_list_options.html', {'subcats': subcats})

def load_items(request):
	category = request.GET.get('category')
	items = Item.objects.filter(categoryID=category).order_by('itemDesc')
	return render(request, 'pos/item_dropdown_list_options.html', {'items': items})
# Create your views here.

def get_transaction(request):
	# if this is a POST request we need to process the form data
	transact_form = TransactionForm()
	if request.method == 'POST':
		data = request.POST.copy()
		if "item" in data:
			transaction = Transaction()
			transaction.camperID = Customer.objects.get(pk=request.GET['Camper'])
			transaction.itemID = Item.objects.get(pk=data.get('item'))
			transaction.save()
		else:
			form = DepositForm(request.POST)
			if form.is_valid():
				deposit = Deposit()
				deposit.camperID = Customer.objects.get(pk=request.GET['Camper'])
				deposit.depositAmount = form.cleaned_data['deposit']
				deposit.depositNotes = form.cleaned_data['notes']
				deposit.save()
	try:
		camperID = request.GET['Camper']
		transactionList = Transaction.objects.filter(camperID=camperID).select_related('itemID').order_by('-transactionDate')
		depositList = Deposit.objects.filter(camperID=camperID).order_by('-depositDate')
		trans_sum = Transaction.calc_current_balance(camperID)
		camper = Customer.objects.get(pk=camperID)
		purchase_form = PurchaseForm()
		deposit_form = DepositForm()
		return render(request = request,
					  template_name = 'pos/transaction.html',
					  context = {'transactionList' : transactionList,
					  			 'depositList' : depositList,
								 'camper' : camper,
								 'form' : transact_form,
								 'purchase_form' : purchase_form,
								 'deposit_form' : deposit_form})

	except MultiValueDictKeyError:
		transact_form = TransactionForm()

		return render(request = request,
					  template_name = 'pos/transaction.html',
					  context = {'form' : transact_form})

pos/templates/pos/index.html
<select>
{% for customer in customer_list %}
	<option value={{ customer.camperID }}>{{ customer.lastName }} {{ customer.firstName }}</option>
{% endfor %}
</select>
<br>
<br>
<select>
{% for category in category_list %}
	<option value={{ category.categoryID }}>{{ category.categoryDesc }}</option>
{% endfor %}
</select>
<select>
{% for category in category_list %}
	<option value={{ category.categoryID }}>{{ category.categoryDesc }}</option>
{% endfor %}
</select>
<select>
{% for item in item_list %}
	<option value={{ item.itemID }}>{{ item.itemDesc }}</option>
{% endfor %}
</select>
<br>
<input type="text" list="items">
	<datalist id="items">
	{% for item in item_list %}
	<option value={{ item.itemID }}>{{ item.itemDesc }}</option>
	{% endfor %}
	</datalist>
</input>
<br>
<select>
{% for category in top_lvl_categories %}
	<option value={{ category.categoryID }}>{{ category.categoryDesc }}</option>
{% endfor %}
</select>

pos/templates/pos/item_dropdown_list_options.html
<option value="">---------</option>
{% for item in items %}
<option value="{{ item.pk }}">{{ item.itemDesc }}</option>
{% endfor %}

pos/templates/pos/subcat_dropdown_list_options.html
<option value="">---------</option>
{% for cat in subcats %}
<option value="{{ cat.pk }}">{{ cat.categoryDesc }}</option>
{% endfor %}

pos/templates/pos/transaction.html
{% extends 'pos/transaction_base.html' %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/pos/style.css' %}">

{% block content %}
<h1>{{ camper.firstName }} {{ camper.lastName }}<br>
Current Balance : {{ camper.currentBalance }}</h1>
<table id='camperTrans'>
	<tr>
	  <th>Category</th>
	  <th>Item</th> 
	  <th>Date</th>
	  <th>Price</th>
	  <th>Delete</th>
	</tr>
{% for transaction in transactionList %}
	<tr>
	  <td>{{ transaction.itemID.categoryID }}
	  <td>{{ transaction.itemID }}</td> 
	  <td>{{ transaction.transactionDate }}</td>
	  <td>{{ transaction.itemID.itemPrice }}</td>
	  <td><form action="{% url 'delete_transaction' transaction.transactionID %}" method='post'>{% csrf_token %}<button>Delete</button></form></td>
	</tr>
{% endfor %}
</table>
<p>Deposits</p>
<table id='camperDeposits'>
	<tr>
	  <th>Amount</th>
	  <th>Date</th>
	  <th>Notes</th>
	  <th>Delete</th>
	</tr>
{% for deposit in depositList %}
	<tr>
	  <td>{{ deposit.depositAmount }}</td>
	  <td>{{ deposit.depositDate }}</td> 
	  <td>{{ deposit.depositNotes }}</td>
	  <td><form action="{% url 'delete_deposit' deposit.depositID %}" method='post'>{% csrf_token %}<button>Delete</button></form></td>
	</tr>
{% endfor %}
</table>
{% endblock %}

pos/templates/pos/transaction_base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/pos/style.css' %}">

<header>
<form action="" method="get">
    {{ form }}
    <input type="submit" value="Submit">
</form>
<p>Add Purchase</p>
<form method="post" id="purchaseForm" data-subcat-url="{% url 'ajax_load_subcat' %}"data-items-url="{% url 'ajax_load_items' %}" novalidate>
	{% csrf_token %}
	{{ purchase_form }}
	<input id="refresh" type="submit" value="Submit">
</form>
<p>Add Deposit</p>
<form method="post" id="depositForm" novalidate>
  {% csrf_token %}
  {{ deposit_form }}
  <input id="refresh" type="submit" value="Submit">
</form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
  	//Checks for any cubcategories underneath main categories
  	$("#id_category").change(function () {
      var url = $("#purchaseForm").attr("data-subcat-url");  // get the url of the `load_cities` view
      var categoryId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/pos/ajax/load-_____/)
        data: {
          'category': categoryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_subcategory").html(data);  // replace the contents of the dropdown with the data that came from the server
        }
      });

    });
  	//Checks for any items directly under a category rather than a subcategory
    $("#id_category").change(function () {
      var url = $("#purchaseForm").attr("data-items-url");
      var categoryId = $(this).val();

      $.ajax({                       // initialize an AJAX request
        url: url,
        data: {
          'category': categoryId
        },
        success: function (data) {
          $("#id_item").html(data); 
        }
      });

    });
    //Checks for items under a category
    $("#id_subcategory").change(function () {
      var url = $("#purchaseForm").attr("data-items-url");  // get the url of the `load_cities` view
      var categoryId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    
        data: {
          'category': categoryId       
        },
        success: function (data) {  
          $("#id_item").html(data);  
        }
      });

    });
  </script>
</header>
{% block content %}
{% endblock %}

pos/templates/pos/transaction_form.html
  <h2>Item Form</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
  </form>